# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLG0ZpqSGwGp4afRN61aMJyl4909ndxH
"""

import os
os.chdir("/content/drive/MyDrive/Digit_Classification_Project")

# make a prediction for a new image
import keras
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.utils import load_img
from PIL import Image
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.models import load_model
from PIL import Image as im

#Importing dataset
(x_train, y_train), (x_test, y_test)=tf.keras.datasets.mnist.load_data()

#Configuring x_train
x_test = x_test.astype('float32')
x_test /= 255

#Load the model
model_name = "LeNet5.h5"
model = tf.keras.models.load_model(model_name)

some_digit = x_test[5]

plt.imshow(some_digit,cmap='gray')

scores = model.predict(some_digit.reshape(-1,28,28,1))
print("Prediction : " + str(argmax(scores)))